### ISSUE TITLE
Editor - Edit Question not available

### ISSUE THREAD

**Issue by joshreid** [surveyjs/surveyjs_react_quickstart#1]
Hi @andrewtelnov 
There appears to be an error with the editor in this context.
The modal for Edit Question fails to open... 
Console:
```
Uncaught TypeError: o is not a function
    at t.show (surveyeditor.min.js:7)
    at t.showQuestionEditor (surveyeditor.min.js:7)
    at Array.<anonymous> (surveyeditor.min.js:7)
    at e.fire (survey.ko.min.js:6)
    at t.editQuestionClick (surveyeditor.min.js:7)
    at HTMLButtonElement.<anonymous> (knockout-latest.debug.js:4255)
```

**Comment by tsv2013** [comment]
It'a a bug - surveyjs editor needs jQuery to show modal dialog.

**Comment by tsv2013** [comment]
First solution - add the following lines into the "surveyjs_react_quickstart\public\index.html" file:
```
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

```

For now I'm working on correct solution - load jQuery and bootstrap as external modules.

**Comment by joshreid** [comment]
Ok cool - meantime that works thanks @tsv2013

**Comment by tsv2013** [comment]
@joshreid please check 0.12.5 update (this repo has been updated also)
