### ISSUE TITLE
KO is undefined

### ISSUE THREAD

**Issue by joshreid** [surveyjs/surveyjs_react_quickstart#2]
Including KO via CDN script tag in the public index.html fixes, but you may want to include dependency to webpack, etc.

Interestingly this only occurs after adding a complex field type, eg multipletext

**Comment by tsv2013** [comment]
Thank you for reporting the issue. The ko import was missed in the `https://github.com/surveyjs/editor/blob/master/src/propertyEditors/propertyTextItemsEditor.ts` file. I've fixed it with the https://github.com/surveyjs/editor/commit/c61dbc27697e9109ee5695d1412da5084e4f0e7d commit.
