### ISSUE TITLE
Does this work with NextJS?

### ISSUE THREAD

**Issue by kamal-choudhary** [surveyjs/surveyjs_react_quickstart#25]
Hi, thank you for the awesome quickstart application.

I am trying to convert this quickstart application from React to NextJS.

But, I have been failing again and again.

Now, I am wondering that whether it is possible that it can work with NextJS or not?

Because this SurveyJS library is a browser-side library. While NextJS is often used for severe side rendering or static generation.

I'll be very thankful to you for your help.

**Comment by tsv2013** [comment]
SurveyJS is a client-side JavaScript library. At this moment it doesn't support server-side rendering.

**Comment by kamal-choudhary** [comment]
Thank you for the quick response.

So, it means that we can't use it with NextJS? Or is there any workaround to make it work with NextJS?

**Comment by kamal-choudhary** [comment]
okay, I got it. Thank you very much for your time!!!

**Comment by kamal-choudhary** [comment]
Posting this solution for future readers.

This is how I am using this library in the NextJS.

```
import React from 'react';
import dynamic from 'next/dynamic';
import PageLoader from './PageLoader';   // Loading Spinner

const Survey = dynamic(() => import('./SurveyView'), {
  loading: () => <PageLoader />,
  ssr: false,
});

export default function SurveyPage() {
  return <Survey />;
}
```
