### ISSUE TITLE
Customization To Properties / Questions in Editor

### ISSUE THREAD

**Issue by pankanis-rushikesh** [surveyjs/surveyjs_react_quickstart#5]
I was trying to customise questions/properties in react-surveyjs editor.
I have survey-react already installed but with this package i am not able to add custom properties.
So as mentioned in [issue#4](https://github.com/surveyjs/surveyjs_react_quickstart/issues/4) 
I installed survey-knockout package.But now I am getting this error.

```
Uncaught Error: Component survey is already registered
    at Object.ko.components.register (knockout.ts:60)
    at Object.<anonymous> (knockout.ts:60)
    at __webpack_require__ (knockout.ts:60)
    at Object.<anonymous> (knockout.ts:60)
    at __webpack_require__ (knockout.ts:60)
    at __webpack_exports__.b (knockout.ts:60)
    at knockout.ts:60
    at webpackUniversalModuleDefinition (knockout.ts:60)
    at Object.<anonymous> (knockout.ts:60)
    at __webpack_require__ (bootstrap 23ee73db2ae19b465b9b:9)
```
I guess this issue is because of conflict between survey-react and survey-knockout packages.
Could you let me know how to use both of them in single App.

**Comment by tsv2013** [comment]
This is because survey-knockout package is loaded twice. I'll update this repo with corresponding sample code.

**Comment by pankanis-rushikesh** [comment]
I would also like to know if you are providing support for React-native also.
I know this is a question not supposed to be asked here but If you are planning to do that it would be great.

**Comment by tsv2013** [comment]
@pankanis-rushikesh Does my first comment help you?

**Comment by pankanis-rushikesh** [comment]
@tsv2013 Yes it did I just added alias for survey-knockout package so that webpack will load it from main node_modules like this : 

```
resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      'survey-knockout': path.resolve(__dirname, 'node_modules', 'survey-knockout')
    }
  }
```

Now the error is gone and I am able to add custom props.
Thanks for the help

**Comment by tsv2013** [comment]
@pankanis-rushikesh Thank you and good luck!
