### ISSUE TITLE
SurveyJS Editor - SignaturePad is not functioning in SurveyEditor using React

### ISSUE THREAD

**Issue by arashzargar** [surveyjs/surveyjs_react_quickstart#6]
Hi,

I have added few lines of code to SurveyEditor.js in order to enable SignaturePad 3rd-party widget to toolbox, but it does not functioning.
It is part of my companies project and it turn to blocking issue. I really appreciate if anyone could help on this matter.

**please uncomment line 129 of App.js to show survey editor!

Thanks & looking forward to hear from you.

```javascript
import React, { Component } from 'react';
import * as SurveyJSEditor from 'surveyjs-editor';
import 'surveyjs-editor/surveyeditor.css';

class SurveyEditor extends Component
 {
    editor;
    componentDidMount() {
        let editorOptions = { showEmbededSurveyTab: true };
        this.editor = new SurveyJSEditor.SurveyEditor('surveyEditorContainer', editorOptions);

        this.editor.toolbox.addItems([
            {
                name: "countries",
                isCopied: true,
                iconName: "icon-default",
                title: "All countries",
                json: {
                    "type": "dropdown",
                    optionsCaption: "Select a country...",
                    choicesByUrl: {
                        url: "https://restcountries.eu/rest/v1/all"
                    }
                }
            },
            {
                name: "Signature",
                isCopied: true,
                iconName: "icon-signaturepad",
                title: "Signature",
                json: {
                    type: "signaturepad",
                    title: "Please enter your signature",
                    name: "sign",
                }
            }
        ]);
        this.editor.saveSurveyFunc = this.saveMySurvey;
    }
    render() {
        return (
            <div id="surveyEditorContainer"></div>
        );
    }
    saveMySurvey = () => {
        console.log(JSON.stringify(this.editor.text));
        console.log(this.editor)
    }
}

export default SurveyEditor;
```

**Comment by andrewtelnov** [comment]
@arashzargar SignaturePad  widget is not a part of SurveyJS library. We added the integration code, but we do not include this library into our project.
Please look at [the demo](https://surveyjs.io/Examples/Library/?id=custom-widget-signaturepad)
You have to add [this library](https://github.com/szimek/signature_pad)

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have to add our custom widget library as well. It contains the integration code.

Thank you,
Andrew

**Comment by EhsanZB** [comment]
I've tried to implement signature pad by importing the respective libraries into index.html and (also directly import on the page using es6 modules) but still it doesn't work and it's not draggable.

`    <script src="https://unpkg.com/signature_pad@2.3.2/dist/signature_pad.min.js"></script>
    <script src="https://unpkg.com/surveyjs-widgets"></script>`

OR

`import 'signature_pad/dist/signature_pad'`
`import 'surveyjs-widgets/surveyjs-widgets'`

**Comment by arashzargar** [comment]
@andrewtelnov Thanks for following up.

As @EhsanZB  mentioned, this is not functioning even if signature_pad import in project.

Regards,
Arash

**Comment by dmitrykurmanov** [comment]
@EhsanZB, @arashzargar we have those examples:

* with es modules (all widgets): https://stackblitz.com/edit/surveyjs-widgets-react

* with es5: https://surveyjs.io/Examples/Library/?id=custom-widget-signaturepad&platform=Reactjs&theme=default

Could you please check it? I think it works.

**Comment by dmitrykurmanov** [comment]
And we will add it it this repo

**Comment by arashzargar** [comment]
@dmitrykurmanov Thanks for respond.

Sadly the issue still remains.
In this link: https://stackblitz.com/edit/surveyjs-widgets-react I've added a file to components folder "SurveyEditor.js", and added a tab called "SurveyJS Editor". 
once you click/drag on SignaturePad item from toolbox, this error appears:

`Error in /turbo_modules/survey-knockout@1.0.1/survey.ko.js:`
`Cannot read property 'getType' of null (835:17)`

appreciate your help :)

**Comment by dmitrykurmanov** [comment]
@arashzargar ok thanks for helping to improve the library! We will check it. We don't have an example with editor and all widgets. So we will implement it in this repo.

**Comment by arashzargar** [comment]
@dmitrykurmanov great! 
looking forward to hear from you :)

**Comment by EhsanZB** [comment]
Thanks @andrewtelnov and @dmitrykurmanov. I really appreciate your help for such improvements.
Looking forward.

**Comment by tsv2013** [comment]
@arashzargar @EhsanZB I've added SurveyJS custom widgets library in this example via the 476f1047076ffa814166a62ee0fa7c1ab6dc7b49 commit in the master. Can you check whether the sample works for you?
The thing with signature pad and the editor was that editor uses the survey-knockout library and should be initialized accordingly. You can check the details in my commit.

**Comment by EhsanZB** [comment]
Thanks @tsv2013 You did awesome job and I really appreciate it. I've just cloned the repo, installed the dependencies, ran the code and boom! Now, we literally have the signature pad in the toolbox by default and it's working great.

**Comment by EhsanZB** [comment]
When added to our project, we get this error:
surveyjs-widgets.js:876 Uncaught TypeError: Unable to process binding "if: function (){return row.koVisible }"

It refers to line 876 of survey-widgets.js:
var signaturePad = new __WEBPACK_IMPORTED_MODULE_0_signature_pad__(canvas);

**Comment by EhsanZB** [comment]
@arashzargar Please check this updates with you project too. Thanks

**Comment by dmitrykurmanov** [comment]
@EhsanZB, could you please provide a minimal example to reproduce your issue on our side?

**Comment by EhsanZB** [comment]
Hi... Still I'm working on it. Basically, I'm making a sample project based on this repo and I'm trying to simulate the same structure of my project. There should be something wrong, because I've even downgraded my dependencies like react from 16 to 15.x but still got the issue. Besides, I'm also waiting for @arashzargar response, he may not have such problem. Thanks

**Comment by EhsanZB** [comment]
By the way, I appreciate if you could tell me what could be possibly the reason(s) for having/producing such errors in knockout (as below), so It would be much more easier for me to debug the issue. Thanks

----> Unable to process binding "if: function (){return row.koVisible }"
----> Unable to process binding "foreach: function (){return { data:koRows,as:'row'} }"
----> Unable to process binding "template: function (){return { name:'survey-rows',data:$data} }"

**Comment by arashzargar** [comment]
Hi All,
thanks @dmitrykurmanov for fix. it's working great on this repo.

@EhsanZB I did not have chance to integrate latest fix with your project yet, let me try and update you. Thanks

**Comment by tsv2013** [comment]
@EhsanZB Probably the templates are outdated for some reason. Can you try to delete the node_modules folder and reinstall them?

**Comment by EhsanZB** [comment]
Hi... I delete the entire node_module folder and reinstall the dependencies, but unfortunately still I got the issue. I was wondering maybe there is some conflicts with other dependencies in my project. I also found out that in your repo, there is no 'react-knockout' dependency mentioned in the package.json but it has been imported in the project!

**Comment by EhsanZB** [comment]
I've applied redux on my react project. Is it possible that redux causes such conflicts?

**Comment by EhsanZB** [comment]
@tsv2013 I've created a sample project. It's just a simple create-react-app in which I've added the related surveyjs dependencies to its package. I appreciate if you could take a look at this repo.

[react-surveyjs-issue6-sampleProject](https://github.com/EhsanZB/react-surveyjs-issue6)

Thanks

**Comment by tsv2013** [comment]
@EhsanZB Sure, I'll take a look.

**Comment by dmitrykurmanov** [comment]
we've added widgets in the our quick start example, please check it :  https://github.com/surveyjs/surveyjs_react_quickstart

**Comment by EhsanZB** [comment]
Hi. I've updated the repo based on your recent changes. Some of the 3rd party libraries are working and properly synced with the editor like `nouislider`, but others likes signature_pad and sortable_list still produce same error. In addition to this, `bootstrap slider` produces a different error (the same error which makes us to open this issue).

I think that your quick starter kit is highly dependent on some development packages and by just only importing the respective surveyJs libraries (like `surveyjs-widgets` , `survey-react` , ...), we can not produce the same result so, we've encountered with such errors or conflicts. The repo that I've just added you guys as contributors is exactly a real world example of using your beautiful SurveyJS library in a project.

**Comment by tsv2013** [comment]
@EhsanZB Thank you for provided repo with the sample project. I've just cloned it (https://github.com/EhsanZB/react-surveyjs-issue6), run "npm i" command and then "npm start". I've got working SurveyJS editor with a set custom widgets:
 - Date picker
 - noUISlider
 - Tag box
 - Signature pad
 - Sortable list
 - Bootstrap slider

I've added each of them to the designer surface:
![image](https://user-images.githubusercontent.com/3013415/35206829-624f7126-ff50-11e7-9808-4c2c4c3d8f98.png)
And switched to the "Test Survey" tab:
![image](https://user-images.githubusercontent.com/3013415/35206864-9942932a-ff50-11e7-977c-30ea3bfbd9bd.png)

I've got all widgets working except the "Bootstrap slider"

**Note:** The "survey-react", "surveyjs-editor", "survey-knockout" and "surveyjs-widgets" libraries have been installed with 1.0.3 version we released last friday.

Can you remove "node_modules" folder, reinstall them and check - whehter you get the same result as I?

**Comment by tsv2013** [comment]
@EhsanZB I've fixed the issue with the "Bootstrap slider" via the https://github.com/surveyjs/widgets/commit/825860f038fcc90aa58f7aa14f14dba20d63b45c commit
Fix will be available in the 1.0.4 update

**Comment by EhsanZB** [comment]
@tsv2013 Thank you so much. Great Job 👍

**Comment by arashzargar** [comment]
@tsv2013 just tested, all works good :) great job!
